#!/bin/sh
unset IFS
set -euf

sudo apt-get update &&
    sudo apt-get install -y clang &&
    sudo apt-get autoclean -y &&
    sudo apt-get clean -y &&
    sudo rm -rf /var/lib/apt/lists/* \
        /var/cache/apt/pkgcache.bin \
        /var/cache/apt/srcpkgcache.bin
